### ISSUE TITLE
create crud to forms 

### ISSUE THREAD

**Issue by FranklysG** [FranklysG/app.pei.digital#10]
after the creating hook useForm, we need the create a crud, they are create, edited, deleted and show data !
all this function are need create inside hook useForm, for after call in page from a function!

this functions you can based on hook useAuth
this case, the example shoud a create, based on hook useAuth

![image](https://user-images.githubusercontent.com/42286289/216871738-58990ffb-3407-4671-a536-00584a2646fa.png)

**Comment by thayna-bezerra** [comment]
Solved this in #13
